// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6CqAC39NECi4BS4LIprds82NgjcvHiFM',
    appId: '1:469419267631:web:f48529c022bc2da45ad8da',
    messagingSenderId: '469419267631',
    projectId: 'projetofinalpdmepsi',
    authDomain: 'projetofinalpdmepsi.firebaseapp.com',
    storageBucket: 'projetofinalpdmepsi.appspot.com',
    measurementId: 'G-33TKC0YJJN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnfRSyni3wubqAYsxfCZdtbDB9Q7Us2E4',
    appId: '1:469419267631:android:3616528a2be49b645ad8da',
    messagingSenderId: '469419267631',
    projectId: 'projetofinalpdmepsi',
    storageBucket: 'projetofinalpdmepsi.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmcQHWmRu-_RQCzS3YG7oAuTShAqcAot4',
    appId: '1:469419267631:ios:3ed80cd46749a2425ad8da',
    messagingSenderId: '469419267631',
    projectId: 'projetofinalpdmepsi',
    storageBucket: 'projetofinalpdmepsi.appspot.com',
    iosClientId: '469419267631-bppeid9569pql5ti21dle7raeem6b3cp.apps.googleusercontent.com',
    iosBundleId: 'br.com.salati.gerenciadortarefas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmcQHWmRu-_RQCzS3YG7oAuTShAqcAot4',
    appId: '1:469419267631:ios:3ed80cd46749a2425ad8da',
    messagingSenderId: '469419267631',
    projectId: 'projetofinalpdmepsi',
    storageBucket: 'projetofinalpdmepsi.appspot.com',
    iosClientId: '469419267631-bppeid9569pql5ti21dle7raeem6b3cp.apps.googleusercontent.com',
    iosBundleId: 'br.com.salati.gerenciadortarefas',
  );
}
